services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-2022
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sqlserver-init.sql:/tmp/sqlserver-init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./sqlserver-init.sql:/tmp/sqlserver-init.sql
    command: >
      bash -c "
      echo 'Waiting for SQL Server to be ready...' &&
      sleep 5 &&
      echo 'Running initialization script...' &&
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P YourStrong@Passw0rd -i /tmp/sqlserver-init.sql -C &&
      echo 'Initialization completed!'
      "

volumes:
  mssql_data:
    driver: local
